package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Polarishq/api-client-go/models"
)

// GetApplicationReader is a Reader for the GetApplication structure.
type GetApplicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetApplicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetApplicationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetApplicationOK creates a GetApplicationOK with default headers values
func NewGetApplicationOK() *GetApplicationOK {
	return &GetApplicationOK{}
}

/*GetApplicationOK handles this case with default header values.

successful operation
*/
type GetApplicationOK struct {
	Payload []*models.ApplicationsResponse
}

func (o *GetApplicationOK) Error() string {
	return fmt.Sprintf("[GET /application][%d] getApplicationOK  %+v", 200, o.Payload)
}

func (o *GetApplicationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationDefault creates a GetApplicationDefault with default headers values
func NewGetApplicationDefault(code int) *GetApplicationDefault {
	return &GetApplicationDefault{
		_statusCode: code,
	}
}

/*GetApplicationDefault handles this case with default header values.

Unexpected error
*/
type GetApplicationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get application default response
func (o *GetApplicationDefault) Code() int {
	return o._statusCode
}

func (o *GetApplicationDefault) Error() string {
	return fmt.Sprintf("[GET /application][%d] GetApplication default  %+v", o._statusCode, o.Payload)
}

func (o *GetApplicationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
