package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetApplicationIDParams creates a new GetApplicationIDParams object
// with the default values initialized.
func NewGetApplicationIDParams() *GetApplicationIDParams {
	var ()
	return &GetApplicationIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApplicationIDParamsWithTimeout creates a new GetApplicationIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApplicationIDParamsWithTimeout(timeout time.Duration) *GetApplicationIDParams {
	var ()
	return &GetApplicationIDParams{

		timeout: timeout,
	}
}

// NewGetApplicationIDParamsWithContext creates a new GetApplicationIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApplicationIDParamsWithContext(ctx context.Context) *GetApplicationIDParams {
	var ()
	return &GetApplicationIDParams{

		Context: ctx,
	}
}

// NewGetApplicationIDParamsWithHTTPClient creates a new GetApplicationIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApplicationIDParamsWithHTTPClient(client *http.Client) *GetApplicationIDParams {
	var ()
	return &GetApplicationIDParams{
		HTTPClient: client,
	}
}

/*GetApplicationIDParams contains all the parameters to send to the API endpoint
for the get application ID operation typically these are written to a http.Request
*/
type GetApplicationIDParams struct {

	/*ID
	  id of the of the application

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get application ID params
func (o *GetApplicationIDParams) WithTimeout(timeout time.Duration) *GetApplicationIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get application ID params
func (o *GetApplicationIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get application ID params
func (o *GetApplicationIDParams) WithContext(ctx context.Context) *GetApplicationIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get application ID params
func (o *GetApplicationIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get application ID params
func (o *GetApplicationIDParams) WithHTTPClient(client *http.Client) *GetApplicationIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get application ID params
func (o *GetApplicationIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get application ID params
func (o *GetApplicationIDParams) WithID(id string) *GetApplicationIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get application ID params
func (o *GetApplicationIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetApplicationIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
