package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLoginProvidersParams creates a new GetLoginProvidersParams object
// with the default values initialized.
func NewGetLoginProvidersParams() *GetLoginProvidersParams {

	return &GetLoginProvidersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLoginProvidersParamsWithTimeout creates a new GetLoginProvidersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLoginProvidersParamsWithTimeout(timeout time.Duration) *GetLoginProvidersParams {

	return &GetLoginProvidersParams{

		timeout: timeout,
	}
}

// NewGetLoginProvidersParamsWithContext creates a new GetLoginProvidersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLoginProvidersParamsWithContext(ctx context.Context) *GetLoginProvidersParams {

	return &GetLoginProvidersParams{

		Context: ctx,
	}
}

// NewGetLoginProvidersParamsWithHTTPClient creates a new GetLoginProvidersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLoginProvidersParamsWithHTTPClient(client *http.Client) *GetLoginProvidersParams {

	return &GetLoginProvidersParams{
		HTTPClient: client,
	}
}

/*GetLoginProvidersParams contains all the parameters to send to the API endpoint
for the get login providers operation typically these are written to a http.Request
*/
type GetLoginProvidersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get login providers params
func (o *GetLoginProvidersParams) WithTimeout(timeout time.Duration) *GetLoginProvidersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get login providers params
func (o *GetLoginProvidersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get login providers params
func (o *GetLoginProvidersParams) WithContext(ctx context.Context) *GetLoginProvidersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get login providers params
func (o *GetLoginProvidersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get login providers params
func (o *GetLoginProvidersParams) WithHTTPClient(client *http.Client) *GetLoginProvidersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get login providers params
func (o *GetLoginProvidersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLoginProvidersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
