package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/Polarishq/api-client-go/models"
)

// GetLoginAuthorizeCallbackReader is a Reader for the GetLoginAuthorizeCallback structure.
type GetLoginAuthorizeCallbackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLoginAuthorizeCallbackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 302:
		result := NewGetLoginAuthorizeCallbackFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetLoginAuthorizeCallbackDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetLoginAuthorizeCallbackFound creates a GetLoginAuthorizeCallbackFound with default headers values
func NewGetLoginAuthorizeCallbackFound() *GetLoginAuthorizeCallbackFound {
	return &GetLoginAuthorizeCallbackFound{}
}

/*GetLoginAuthorizeCallbackFound handles this case with default header values.

Redirecting back to front end defined redirect
*/
type GetLoginAuthorizeCallbackFound struct {
	Location string
}

func (o *GetLoginAuthorizeCallbackFound) Error() string {
	return fmt.Sprintf("[GET /login/authorize/callback][%d] getLoginAuthorizeCallbackFound ", 302)
}

func (o *GetLoginAuthorizeCallbackFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location
	o.Location = response.GetHeader("Location")

	return nil
}

// NewGetLoginAuthorizeCallbackDefault creates a GetLoginAuthorizeCallbackDefault with default headers values
func NewGetLoginAuthorizeCallbackDefault(code int) *GetLoginAuthorizeCallbackDefault {
	return &GetLoginAuthorizeCallbackDefault{
		_statusCode: code,
	}
}

/*GetLoginAuthorizeCallbackDefault handles this case with default header values.

Unexpected error
*/
type GetLoginAuthorizeCallbackDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get login authorize callback default response
func (o *GetLoginAuthorizeCallbackDefault) Code() int {
	return o._statusCode
}

func (o *GetLoginAuthorizeCallbackDefault) Error() string {
	return fmt.Sprintf("[GET /login/authorize/callback][%d] GetLoginAuthorizeCallback default  %+v", o._statusCode, o.Payload)
}

func (o *GetLoginAuthorizeCallbackDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
