package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostLoginOauthRevokeParams creates a new PostLoginOauthRevokeParams object
// with the default values initialized.
func NewPostLoginOauthRevokeParams() *PostLoginOauthRevokeParams {
	var ()
	return &PostLoginOauthRevokeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLoginOauthRevokeParamsWithTimeout creates a new PostLoginOauthRevokeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLoginOauthRevokeParamsWithTimeout(timeout time.Duration) *PostLoginOauthRevokeParams {
	var ()
	return &PostLoginOauthRevokeParams{

		timeout: timeout,
	}
}

// NewPostLoginOauthRevokeParamsWithContext creates a new PostLoginOauthRevokeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLoginOauthRevokeParamsWithContext(ctx context.Context) *PostLoginOauthRevokeParams {
	var ()
	return &PostLoginOauthRevokeParams{

		Context: ctx,
	}
}

// NewPostLoginOauthRevokeParamsWithHTTPClient creates a new PostLoginOauthRevokeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLoginOauthRevokeParamsWithHTTPClient(client *http.Client) *PostLoginOauthRevokeParams {
	var ()
	return &PostLoginOauthRevokeParams{
		HTTPClient: client,
	}
}

/*PostLoginOauthRevokeParams contains all the parameters to send to the API endpoint
for the post login oauth revoke operation typically these are written to a http.Request
*/
type PostLoginOauthRevokeParams struct {

	/*Body*/
	Body PostLoginOauthRevokeBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post login oauth revoke params
func (o *PostLoginOauthRevokeParams) WithTimeout(timeout time.Duration) *PostLoginOauthRevokeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post login oauth revoke params
func (o *PostLoginOauthRevokeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post login oauth revoke params
func (o *PostLoginOauthRevokeParams) WithContext(ctx context.Context) *PostLoginOauthRevokeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post login oauth revoke params
func (o *PostLoginOauthRevokeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post login oauth revoke params
func (o *PostLoginOauthRevokeParams) WithHTTPClient(client *http.Client) *PostLoginOauthRevokeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post login oauth revoke params
func (o *PostLoginOauthRevokeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post login oauth revoke params
func (o *PostLoginOauthRevokeParams) WithBody(body PostLoginOauthRevokeBody) *PostLoginOauthRevokeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post login oauth revoke params
func (o *PostLoginOauthRevokeParams) SetBody(body PostLoginOauthRevokeBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostLoginOauthRevokeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
