package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostLoginTokenParams creates a new PostLoginTokenParams object
// with the default values initialized.
func NewPostLoginTokenParams() *PostLoginTokenParams {
	var ()
	return &PostLoginTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostLoginTokenParamsWithTimeout creates a new PostLoginTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostLoginTokenParamsWithTimeout(timeout time.Duration) *PostLoginTokenParams {
	var ()
	return &PostLoginTokenParams{

		timeout: timeout,
	}
}

// NewPostLoginTokenParamsWithContext creates a new PostLoginTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostLoginTokenParamsWithContext(ctx context.Context) *PostLoginTokenParams {
	var ()
	return &PostLoginTokenParams{

		Context: ctx,
	}
}

// NewPostLoginTokenParamsWithHTTPClient creates a new PostLoginTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostLoginTokenParamsWithHTTPClient(client *http.Client) *PostLoginTokenParams {
	var ()
	return &PostLoginTokenParams{
		HTTPClient: client,
	}
}

/*PostLoginTokenParams contains all the parameters to send to the API endpoint
for the post login token operation typically these are written to a http.Request
*/
type PostLoginTokenParams struct {

	/*Body*/
	Body PostLoginTokenBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post login token params
func (o *PostLoginTokenParams) WithTimeout(timeout time.Duration) *PostLoginTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post login token params
func (o *PostLoginTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post login token params
func (o *PostLoginTokenParams) WithContext(ctx context.Context) *PostLoginTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post login token params
func (o *PostLoginTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post login token params
func (o *PostLoginTokenParams) WithHTTPClient(client *http.Client) *PostLoginTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post login token params
func (o *PostLoginTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post login token params
func (o *PostLoginTokenParams) WithBody(body PostLoginTokenBody) *PostLoginTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post login token params
func (o *PostLoginTokenParams) SetBody(body PostLoginTokenBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostLoginTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
