package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// TimeRange time range
// swagger:model TimeRange
type TimeRange struct {

	// earliest
	Earliest *string `json:"earliest,omitempty"`

	// latest
	Latest *string `json:"latest,omitempty"`
}

// Validate validates this time range
func (m *TimeRange) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
